# Site settings
title: Hello i'm Josh
email: josh@thisemailwontwork
description: "Hi, my name is josh and im currently building my website and learning jekyll. cheers!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: JoshuaFerguso10
github_username:  jeferguson

# Build settings
markdown: kramdown
permalink: pretty
