# Site settings
title: Joshua Ferguson
email: josh@no_email
description: "Hi, my name is Josh!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: JoshuaFerguso10
github_username:  jeferguson

# Build settings
markdown: kramdown
permalink: pretty
