# Site settings
title: Joshua Ezra Ferguson
email: josh@jeferguson.com
description: 
baseurl: ""
url: "http://jeferguson.github.io"
twitter_username: JoshuaFerguso10
github_username:  jeferguson
path: ""

# Build settings
markdown: kramdown
permalink: pretty
